#define BRICK_WIDTH     40
#define BRICK_HEIGHT    15
#define BRICK_SPACING   5

#define BRICK_COLUMN_HEIGHT 8

#define BRICK_COLOR_DEFAULT 0x0000FF00 //Green
#define BRICK_COLOR_ACTIVE  0x00FFFF00 //Yellow
